FROM node:20-alpine3.20
RUN mkdir -p /home/app
WORKDIR /home/app
RUN mkdir -p public
RUN mkdir -p public/temp
RUN mkdir -p logs
COPY package.json .
COPY ./prisma .
RUN npx prisma generate
RUN npm i --omit=dev
COPY . .
EXPOSE 8080
CMD [ "npm" ,"start"]

