FROM node:20-alpine3.19

RUN mkdir -p /home/app
WORKDIR /home/app

COPY package*.json /home/app
RUN npm install

COPY . /home/app
#RUN bash -c "sleep 60"
RUN npm run build
EXPOSE 8080
# RUN npm run dockerStart
CMD ["node","./dist/app.js"]