services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: npm run dockerStart 
      # - npx prisma migrate deploy 
      #-  #>
    #  bash -c "npx prisma migrate deploy && npm run dockerStart"
    ports:
      - "8080:8080"
    links:
      - db
    restart: always
  db:
    build: 
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=informe5
    volumes:
      - dbvol:/var/lib/mysql
    restart: always
volumes:
  dbvol:
