services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev    
    ports:
      - "8090:8080"
    links:
      - db
    restart: always
    volumes:
      - /var/www/i5backenddocker/public:/home/app/public
      - logs:/home/app/logs

    develop:
      watch:
        - action: rebuild
          path: /package.json
        - action: sync+restart
          path: ./src
          target: /home/app/src
          
  db:
    build: 
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=informe5
    volumes:
      - dbvol:/var/lib/mysql
    restart: always
volumes:
  dbvol:
  logs:

# - action: sync+restart
        #   path: .
        #   target: /home/app
        #   ignore:
        #     - node_modules
        #     - dist
        #     - public
        #     - logs